### ISSUE TITLE
Openflight Data has changed

### ISSUE THREAD

**Issue by J0N3X** [commenthol/openflights-data#1]
Hi!

I just used a good 2+ hours debugging my project and i ended up to debug this package. Openflight has changed their data, there is now one extra column, mostly saying "OurAirports". I don't have the purpose of this data, but to fix this issue, you need to change the headers in data.js, row 84, new row with for example "ExtraData" as the new input. Sorry i don't time to do you a pr for you, but go ahead and test this.

To produce the error, please make a fresh install of the package, loadData().then((res)=>{console.log(res.iata)}) and boom, there you have an empty object of airport by iata. 

--
Joonas

**Comment by J0N3X** [comment]
And sorry for the format of issue report, it's my first time to create one.

**Comment by commenthol** [comment]
v1.0.3 is published at npm. Have fun with it and thanks.
